### PR TITLE
Add `url_mode` for downloading images

### PR DESCRIPTION
**Pull request by developius**
Signed-off-by: Finnian Anderson <get@finnian.io>

### CODE REVIEW

**Comment by alexellis** [comment]
Hey @developius is this tested for all three modes now? Can we also update the README please?

**Comment by developius** [comment]
Hey @alexellis will retest & update the README early next week, time permitting 👍

**Comment by alexellis** [comment]
Sooner the better.. I have a big talk Thursday would be awesome to show this!

**Comment by developius** [comment]
@alexellis tested and updated docs 👍

**Comment by alexellis** [comment]
Thanks @developius I'll build a new image and publish it - incrementing the tag. We can then use that for the store?

**Comment by developius** [comment]
Awesome 💯

**Pull request merged**
